{
    'name': 'Real Estate Christian',
    'version': '1.0',
    'summary': 'Modulo de practica de inmobiliaria',
    'description': 'Gestion de propiedades inmobiliarias.',
    'author': 'Christian',
    'category': 'Real Estate',
    'license': 'LGPL-3',
    'depends': ['base'],
    'data': [
        'security/real_estate_security.xml',
        'security/ir.model.access.csv',
        'data/real_estate_property_stage_data.xml',
        'data/ir_cron.xml',
        'views/real_estate_property_stage_views.xml',
        'views/real_estate_property_incidence_views.xml',
        'views/real_estate_property_views.xml',
        'views/real_estate_visit_views.xml',
        'views/real_estate_category_views.xml',
        'views/real_estate_offer_views.xml',
        'views/real_estate_contract_views.xml',
        'views/real_estate_agent_views.xml',
        'views/real_estate_owner_views.xml',
        'views/real_estate_menu_items.xml',
        'wizard/real_estate_property_stage_wizard_views.xml',
        'wizard/real_estate_visit_batch_wizard_views.xml',
        'report/real_estate_property_report.xml',
        'report/real_estate_property_list_report.xml',
        'report/real_estate_contract_report.xml',
        'wizard/real_estate_visit_state_wizard.xml',
        'report/real_estate_offer_report.xml',
    ],
    'application': True,
    'installable': True,
}
