{
    "name": "Real Estate Ramón",
    "version": "1.0",
    "summary": "Real estate management module",
    "description": "Module to manage real estate properties, agents, clients and many more...",
    "author": "Ramón",
    "category": "Real Estate",
    "depends": ["base",],
    "data": [
        "security/ir.model.access.csv",
        "views/realestate_property_views.xml",
        "views/realestate_visit_views.xml",
        "views/realestate_category_views.xml",
        "views/realestate_offer_views.xml",
        "views/realestate_contract_views.xml",
        "views/realestate_menuitems.xml",
    ],
    "installable": True,
    "application": True,
}