{
    "name": "Real Estate Ramón",
    "version": "1.0",
    "summary": "Real estate management module",
    "description": "Module to manage real estate properties, agents, clients and many more...",
    "author": "Ramón",
    "category": "Real Estate",
    "depends": ["base",],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/realestate_property_views.xml",
        "views/realestate_visit_views.xml",
        "views/realestate_category_views.xml",
        "views/realestate_offer_views.xml",
        "views/realestate_contract_views.xml",
        "views/realestate_menuitems.xml",
        "wizard/realestate_property_stage_wizard_views.xml",
        "wizard/realestate_visit_wizard_views.xml",
        "wizard/realestate_visit_status_wizard_views.xml",
        "report/realestate_property_report.xml",
        "report/realestate_property_templates.xml",
        "report/realestate_property_simple_report.xml",
        "report/realestate_property_simple_templates.xml",
        "report/realestate_contract_report.xml",
        "report/realestate_contract_templates.xml",
        "report/realestate_offer_report.xml",
        "report/realestate_offer_templates.xml",
    ],
    "installable": True,
    "application": True,
}